"""Generate weak default implementations for every il2cpp_* API function.

Each stub logs "UNIMPLEMENTED <name>" on its first call and returns 0. All API functions return an
integer or a pointer (checked against il2cpp-api-functions.h), so "return 0 in x0, ignore the
arguments" is ABI-safe for any of them. Real implementations live in other .c files as normal
(strong) definitions and override these at link time.

usage: gen_stubs.py il2cpp-api-functions.h OUTDIR
"""
import os
import re
import sys

header, outdir = sys.argv[1], sys.argv[2]
names = []
for line in open(header, encoding="utf-8"):
    m = re.match(r"\s*DO_API(?:_NO_RETURN)?\(\s*[^,]+,\s*(il2cpp_\w+)\s*,", line)
    if m and m.group(1) not in names:
        names.append(m.group(1))

os.makedirs(outdir, exist_ok=True)
with open(os.path.join(outdir, "stubs.c"), "w", newline="\n") as o:
    o.write("// Generated by gen_stubs.py — do not edit.\n#include \"../il2mono.h\"\n\n")
    o.write(f"const char* const il2mono_api_names[IL2MONO_API_COUNT] = {{\n")
    for n in names:
        o.write(f'    "{n}",\n')
    o.write("};\n\n")
    for i, n in enumerate(names):
        o.write(f"__attribute__((weak, visibility(\"default\"))) uintptr_t {n}(void) "
                f"{{ il2mono_unimplemented({i}); return 0; }}\n")
with open(os.path.join(outdir, "api_count.h"), "w", newline="\n") as o:
    o.write(f"#define IL2MONO_API_COUNT {len(names)}\n")
print(f"{len(names)} stubs -> {outdir}")
