#!/usr/bin/env python3
"""Generate app/src/main/cpp/steam_api_stub.c: an ARM64 libsteam_api.so for native ARM64 Mono.

Valheim quits unless SteamAPI_Init() succeeds and Steamworks.NET's CSteamAPIContext.Init() gets a
pipe, a user and non-NULL interface pointers. Under emulated Mono the Goldberg emulator provides that;
under native ARM64 Mono the game's P/Invokes land in an ARM64 library next to the runtime instead, and
this stub plays Steam in offline single-player mode: every call "works", every query answers a fixed,
plausible value, everything else returns zero.

Input: steamworks_net_imports.tsv (one row per DllImport of Valheim's Steamworks.NET, with the ABI of
its return value). Every entry point gets a typed export so float and struct returns use the right
registers. Answers that differ from zero live in OVERRIDES below.

Usage: python gen_steam_stub.py [imports.tsv] [output.c]
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", ".."))

STEAM_ID = "76561197960287930ULL"   # a valid individual SteamID (universe 1, type 1)
APP_ID = "892970U"                  # Valheim

# entry point -> C expression returned instead of zero
OVERRIDES = {
    "SteamAPI_Init": "1",
    "SteamAPI_IsSteamRunning": "1",
    "SteamAPI_RestartAppIfNecessary": "0",
    "SteamAPI_GetHSteamPipe": "1",
    "SteamAPI_GetHSteamUser": "1",
    "SteamAPI_ISteamUser_GetHSteamUser": "1",
    "SteamInternal_ContextInit": "(uint64_t)(uintptr_t)vd_interface",
    "SteamInternal_CreateInterface": "(uint64_t)(uintptr_t)vd_interface",
    "SteamInternal_FindOrCreateUserInterface": "(uint64_t)(uintptr_t)vd_interface",
    "SteamAPI_ISteamUser_GetSteamID": STEAM_ID,
    "SteamAPI_ISteamUser_BLoggedOn": "0",          # Steam in offline mode, like the Goldberg setup
    "SteamAPI_ISteamFriends_GetPersonaName": "(uint64_t)(uintptr_t)vd_persona",
    "SteamAPI_ISteamFriends_GetFriendPersonaName": "(uint64_t)(uintptr_t)vd_persona",
    "SteamAPI_ISteamApps_GetCurrentGameLanguage": "(uint64_t)(uintptr_t)vd_language",
    "SteamAPI_ISteamApps_GetAvailableGameLanguages": "(uint64_t)(uintptr_t)vd_language",
    "SteamAPI_ISteamApps_BIsSubscribed": "1",
    "SteamAPI_ISteamApps_BIsSubscribedApp": "1",
    "SteamAPI_ISteamApps_GetAppOwner": STEAM_ID,
    "SteamAPI_ISteamUtils_GetAppID": APP_ID,
    "SteamAPI_ISteamUtils_GetIPCountry": "(uint64_t)(uintptr_t)vd_country",
    "SteamAPI_ISteamUserStats_RequestCurrentStats": "1",
    "SteamAPI_ISteamNetworkingSockets_InitAuthentication": "100",   # k_ESteamNetworkingAvailability_Current
}

# every ISteamClient_GetISteamXxx accessor returns the dummy interface
INTERFACE_PREFIX = "SteamAPI_ISteamClient_GetISteam"

STRUCTS = {
    "SteamIPAddress_t": "struct __attribute__((packed)) { uint8_t ipv6[16]; int32_t type; }",
    "InputDigitalActionData_t": "struct __attribute__((packed)) { uint8_t state; uint8_t active; }",
    "InputAnalogActionData_t": "struct __attribute__((packed)) { int32_t mode; float x; float y; uint8_t active; }",
    "InputMotionData_t": "struct { float rot_quat[4]; float pos_accel[3]; float rot_vel[3]; }",
}


def main():
    tsv = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "steamworks_net_imports.tsv")
    out = sys.argv[2] if len(sys.argv) > 2 else os.path.join(ROOT, "app", "src", "main", "cpp", "steam_api_stub.c")
    rows = []
    with open(tsv, encoding="utf-8") as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue
            lib, name, managed, abi = line.rstrip("\n").split("\t")
            if lib == "steam_api":
                rows.append((name, managed, abi))

    lines = [
        "/* Generated by tools/steam-stub-arm64/gen_steam_stub.py from steamworks_net_imports.tsv. Do not edit. */",
        "/* ARM64 libsteam_api.so for native ARM64 Mono: Steam in offline single-player mode (see the generator). */",
        "#include <stdint.h>",
        "",
        "#define VD_EXPORT __attribute__((visibility(\"default\")))",
        "",
        "/* Interface objects are only ever passed back to this library, so one zeroed block serves them all. */",
        "static uint64_t vd_interface_storage[64];",
        "static void* const vd_interface = vd_interface_storage;",
        "static const char vd_persona[] = \"Viking\";",
        "static const char vd_language[] = \"english\";",
        "static const char vd_country[] = \"US\";",
        "",
    ]
    for tag, decl in STRUCTS.items():
        lines.append(f"typedef {decl} vd_{tag};")
    lines.append("")

    unused = set(OVERRIDES)
    for name, managed, abi in rows:
        value = OVERRIDES.get(name)
        if value is None and name.startswith(INTERFACE_PREFIX):
            value = "(uint64_t)(uintptr_t)vd_interface"
        unused.discard(name)
        if abi == "void":
            lines.append(f"VD_EXPORT void {name}(void) {{}}")
        elif abi == "f32":
            lines.append(f"VD_EXPORT float {name}(void) {{ return 0.0f; }}")
        elif abi == "f64":
            lines.append(f"VD_EXPORT double {name}(void) {{ return 0.0; }}")
        elif abi.startswith("struct:"):
            tag = abi.split(":", 1)[1]
            lines.append(f"VD_EXPORT vd_{tag} {name}(void) {{ vd_{tag} r = {{0}}; return r; }}")
        else:
            lines.append(f"VD_EXPORT uint64_t {name}(void) {{ return {value or '0'}; }}")
    if unused:
        sys.exit(f"overrides for unknown entry points: {sorted(unused)}")

    with open(out, "w", newline="\n", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print(f"STEAM_STUB entry_points={len(rows)} overrides={len(OVERRIDES)} output={out}")


if __name__ == "__main__":
    main()
