/* Generated by tools/steam-stub-arm64/gen_steam_stub.py from steamworks_net_imports.tsv. Do not edit. */
/* ARM64 libsteam_api.so for native ARM64 Mono: Steam in offline single-player mode (see the generator). */
#include <stdint.h>

#define VD_EXPORT __attribute__((visibility("default")))

/* Interface objects are only ever passed back to this library, so one zeroed block serves them all. */
static uint64_t vd_interface_storage[64];
static void* const vd_interface = vd_interface_storage;
static const char vd_persona[] = "Viking";
static const char vd_language[] = "english";
static const char vd_country[] = "US";

typedef struct __attribute__((packed)) { uint8_t ipv6[16]; int32_t type; } vd_SteamIPAddress_t;
typedef struct __attribute__((packed)) { uint8_t state; uint8_t active; } vd_InputDigitalActionData_t;
typedef struct __attribute__((packed)) { int32_t mode; float x; float y; uint8_t active; } vd_InputAnalogActionData_t;
typedef struct { float rot_quat[4]; float pos_accel[3]; float rot_vel[3]; } vd_InputMotionData_t;

VD_EXPORT uint64_t SteamAPI_GetHSteamPipe(void) { return 1; }
VD_EXPORT uint64_t SteamAPI_GetHSteamUser(void) { return 1; }
VD_EXPORT uint64_t SteamAPI_GetSteamInstallPath(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamAppList_GetAppBuildId(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamAppList_GetAppInstallDir(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamAppList_GetAppName(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamAppList_GetInstalledApps(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamAppList_GetNumInstalledApps(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_BGetDLCDataByIndex(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_BIsAppInstalled(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_BIsCybercafe(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_BIsDlcInstalled(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_BIsLowViolence(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_BIsSubscribed(void) { return 1; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_BIsSubscribedApp(void) { return 1; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_BIsSubscribedFromFamilySharing(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_BIsSubscribedFromFreeWeekend(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_BIsTimedTrial(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_BIsVACBanned(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_GetAppBuildId(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_GetAppInstallDir(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_GetAppOwner(void) { return 76561197960287930ULL; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_GetAvailableGameLanguages(void) { return (uint64_t)(uintptr_t)vd_language; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_GetCurrentBetaName(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_GetCurrentGameLanguage(void) { return (uint64_t)(uintptr_t)vd_language; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_GetDLCCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_GetDlcDownloadProgress(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_GetEarliestPurchaseUnixTime(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_GetFileDetails(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_GetInstalledDepots(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_GetLaunchCommandLine(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamApps_GetLaunchQueryParam(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamApps_InstallDLC(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamApps_MarkContentCorrupt(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamApps_RequestAllProofOfPurchaseKeys(void) {}
VD_EXPORT void SteamAPI_ISteamApps_RequestAppProofOfPurchaseKey(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamApps_SetDlcContext(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamApps_UninstallDLC(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamClient_BReleaseSteamPipe(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_BShutdownIfAllPipesClosed(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_ConnectToGlobalUser(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_CreateLocalUser(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_CreateSteamPipe(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetIPCCallCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamAppList(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamApps(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamController(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamFriends(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamGameSearch(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamGameServer(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamGameServerStats(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamGenericInterface(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamHTMLSurface(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamHTTP(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamInput(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamInventory(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamMatchmaking(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamMatchmakingServers(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamMusic(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamMusicRemote(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamNetworking(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamParentalSettings(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamParties(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamRemotePlay(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamRemoteStorage(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamScreenshots(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamUGC(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamUser(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamUserStats(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamUtils(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamAPI_ISteamClient_GetISteamVideo(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT void SteamAPI_ISteamClient_ReleaseUser(void) {}
VD_EXPORT void SteamAPI_ISteamClient_SetLocalIPBinding(void) {}
VD_EXPORT void SteamAPI_ISteamClient_SetWarningMessageHook(void) {}
VD_EXPORT void SteamAPI_ISteamFriends_ActivateGameOverlay(void) {}
VD_EXPORT void SteamAPI_ISteamFriends_ActivateGameOverlayInviteDialog(void) {}
VD_EXPORT void SteamAPI_ISteamFriends_ActivateGameOverlayInviteDialogConnectString(void) {}
VD_EXPORT void SteamAPI_ISteamFriends_ActivateGameOverlayRemotePlayTogetherInviteDialog(void) {}
VD_EXPORT void SteamAPI_ISteamFriends_ActivateGameOverlayToStore(void) {}
VD_EXPORT void SteamAPI_ISteamFriends_ActivateGameOverlayToUser(void) {}
VD_EXPORT void SteamAPI_ISteamFriends_ActivateGameOverlayToWebPage(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamFriends_BHasEquippedProfileItem(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamFriends_ClearRichPresence(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamFriends_CloseClanChatWindowInSteam(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_DownloadClanActivityCounts(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_EnumerateFollowingList(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetChatMemberByIndex(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetClanActivityCounts(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetClanByIndex(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetClanChatMemberCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetClanChatMessage(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetClanCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetClanName(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetClanOfficerByIndex(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetClanOfficerCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetClanOwner(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetClanTag(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetCoplayFriend(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetCoplayFriendCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFollowerCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendByIndex(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendCoplayGame(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendCoplayTime(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendCountFromSource(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendFromSourceByIndex(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendGamePlayed(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendMessage(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendPersonaName(void) { return (uint64_t)(uintptr_t)vd_persona; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendPersonaNameHistory(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendPersonaState(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendRelationship(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendRichPresence(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendRichPresenceKeyByIndex(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendRichPresenceKeyCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendSteamLevel(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendsGroupCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendsGroupIDByIndex(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendsGroupMembersCount(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamFriends_GetFriendsGroupMembersList(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetFriendsGroupName(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetLargeFriendAvatar(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetMediumFriendAvatar(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetNumChatsWithUnreadPriorityMessages(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetPersonaName(void) { return (uint64_t)(uintptr_t)vd_persona; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetPersonaState(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetPlayerNickname(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetProfileItemPropertyString(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetProfileItemPropertyUint(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetSmallFriendAvatar(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_GetUserRestrictions(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_HasFriend(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_InviteUserToGame(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_IsClanChatAdmin(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_IsClanChatWindowOpenInSteam(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_IsClanOfficialGameGroup(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_IsClanPublic(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_IsFollowing(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_IsUserInSource(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_JoinClanChatRoom(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_LeaveClanChatRoom(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_OpenClanChatWindowInSteam(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_RegisterProtocolInOverlayBrowser(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_ReplyToFriendMessage(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_RequestClanOfficerList(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_RequestEquippedProfileItems(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamFriends_RequestFriendRichPresence(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamFriends_RequestUserInformation(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_SendClanChatMessage(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamFriends_SetInGameVoiceSpeaking(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamFriends_SetListenForFriendsMessages(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamFriends_SetPersonaName(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamFriends_SetPlayedWith(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamFriends_SetRichPresence(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameSearch_AcceptGame(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameSearch_AddGameSearchParams(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameSearch_CancelRequestPlayersForGame(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameSearch_DeclineGame(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameSearch_EndGame(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameSearch_EndGameSearch(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameSearch_HostConfirmGameStart(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameSearch_RequestPlayersForGame(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameSearch_RetrieveConnectionDetails(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameSearch_SearchForGameSolo(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameSearch_SearchForGameWithLobby(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameSearch_SetConnectionDetails(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameSearch_SetGameHostParams(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameSearch_SubmitPlayerResult(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServerStats_ClearUserAchievement(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServerStats_GetUserAchievement(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServerStats_GetUserStatFloat(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServerStats_GetUserStatInt32(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServerStats_RequestUserStats(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServerStats_SetUserAchievement(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServerStats_SetUserStatFloat(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServerStats_SetUserStatInt32(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServerStats_StoreUserStats(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServerStats_UpdateUserAvgRateStat(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServer_AssociateWithClan(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServer_BLoggedOn(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServer_BSecure(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServer_BUpdateUserData(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServer_BeginAuthSession(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamGameServer_CancelAuthTicket(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_ClearAllKeyValues(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamGameServer_ComputeNewPlayerCompatibility(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServer_CreateUnauthenticatedUserConnection(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamGameServer_EndAuthSession(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamGameServer_GetAuthSessionTicket(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamGameServer_GetGameplayStats(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamGameServer_GetNextOutgoingPacket(void) { return 0; }
VD_EXPORT vd_SteamIPAddress_t SteamAPI_ISteamGameServer_GetPublicIP(void) { vd_SteamIPAddress_t r = {0}; return r; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServer_GetServerReputation(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServer_GetSteamID(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServer_HandleIncomingPacket(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamGameServer_LogOff(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_LogOn(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_LogOnAnonymous(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamGameServer_RequestUserGroupStatus(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServer_SendUserConnectAndAuthenticate_DEPRECATED(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamGameServer_SendUserDisconnect_DEPRECATED(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_SetAdvertiseServerActive(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_SetBotPlayerCount(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_SetDedicatedServer(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_SetGameData(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_SetGameDescription(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_SetGameTags(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_SetKeyValue(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_SetMapName(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_SetMaxPlayerCount(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_SetModDir(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_SetPasswordProtected(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_SetProduct(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_SetRegion(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_SetServerName(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_SetSpectatorPort(void) {}
VD_EXPORT void SteamAPI_ISteamGameServer_SetSpectatorServerName(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamGameServer_UserHasLicenseForApp(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamGameServer_WasRestartRequested(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamHTMLSurface_AddHeader(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_AllowStartRequest(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_CopyToClipboard(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamHTMLSurface_CreateBrowser(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamHTMLSurface_ExecuteJavascript(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_FileLoadDialogResponse(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_Find(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_GetLinkAtPosition(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_GoBack(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_GoForward(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamHTMLSurface_Init(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamHTMLSurface_JSDialogResponse(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_KeyChar(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_KeyDown(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_KeyUp(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_LoadURL(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_MouseDoubleClick(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_MouseDown(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_MouseMove(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_MouseUp(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_MouseWheel(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_OpenDeveloperTools(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_PasteFromClipboard(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_Reload(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_RemoveBrowser(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_SetBackgroundMode(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_SetCookie(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_SetDPIScalingFactor(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_SetHorizontalScroll(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_SetKeyFocus(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_SetPageScaleFactor(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_SetSize(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_SetVerticalScroll(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamHTMLSurface_Shutdown(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamHTMLSurface_StopFind(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_StopLoad(void) {}
VD_EXPORT void SteamAPI_ISteamHTMLSurface_ViewSource(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_CreateCookieContainer(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_CreateHTTPRequest(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_DeferHTTPRequest(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_GetHTTPDownloadProgressPct(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_GetHTTPRequestWasTimedOut(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_GetHTTPResponseBodyData(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_GetHTTPResponseBodySize(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_GetHTTPResponseHeaderSize(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_GetHTTPResponseHeaderValue(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_GetHTTPStreamingResponseBodyData(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_PrioritizeHTTPRequest(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_ReleaseCookieContainer(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_ReleaseHTTPRequest(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_SendHTTPRequest(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_SendHTTPRequestAndStreamResponse(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_SetCookie(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_SetHTTPRequestAbsoluteTimeoutMS(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_SetHTTPRequestContextValue(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_SetHTTPRequestCookieContainer(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_SetHTTPRequestGetOrPostParameter(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_SetHTTPRequestHeaderValue(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_SetHTTPRequestNetworkActivityTimeout(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_SetHTTPRequestRawPostBody(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_SetHTTPRequestRequiresVerifiedCertificate(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamHTTP_SetHTTPRequestUserAgentInfo(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamInput_ActivateActionSet(void) {}
VD_EXPORT void SteamAPI_ISteamInput_ActivateActionSetLayer(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamInput_BNewDataAvailable(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_BWaitForData(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamInput_DeactivateActionSetLayer(void) {}
VD_EXPORT void SteamAPI_ISteamInput_DeactivateAllActionSetLayers(void) {}
VD_EXPORT void SteamAPI_ISteamInput_EnableActionEventCallbacks(void) {}
VD_EXPORT void SteamAPI_ISteamInput_EnableDeviceCallbacks(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetActionOriginFromXboxOrigin(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetActionSetHandle(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetActiveActionSetLayers(void) { return 0; }
VD_EXPORT vd_InputAnalogActionData_t SteamAPI_ISteamInput_GetAnalogActionData(void) { vd_InputAnalogActionData_t r = {0}; return r; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetAnalogActionHandle(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetAnalogActionOrigins(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetConnectedControllers(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetControllerForGamepadIndex(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetCurrentActionSet(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetDeviceBindingRevision(void) { return 0; }
VD_EXPORT vd_InputDigitalActionData_t SteamAPI_ISteamInput_GetDigitalActionData(void) { vd_InputDigitalActionData_t r = {0}; return r; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetDigitalActionHandle(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetDigitalActionOrigins(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetGamepadIndexForController(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetGlyphForActionOrigin_Legacy(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetGlyphForXboxOrigin(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetGlyphPNGForActionOrigin(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetGlyphSVGForActionOrigin(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetInputTypeForHandle(void) { return 0; }
VD_EXPORT vd_InputMotionData_t SteamAPI_ISteamInput_GetMotionData(void) { vd_InputMotionData_t r = {0}; return r; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetRemotePlaySessionID(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetSessionInputConfigurationSettings(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetStringForActionOrigin(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetStringForAnalogActionName(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetStringForDigitalActionName(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_GetStringForXboxOrigin(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_Init(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamInput_Legacy_TriggerHapticPulse(void) {}
VD_EXPORT void SteamAPI_ISteamInput_Legacy_TriggerRepeatedHapticPulse(void) {}
VD_EXPORT void SteamAPI_ISteamInput_RunFrame(void) {}
VD_EXPORT void SteamAPI_ISteamInput_SetDualSenseTriggerEffect(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamInput_SetInputActionManifestFilePath(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamInput_SetLEDColor(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamInput_ShowBindingPanel(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInput_Shutdown(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamInput_StopAnalogActionMomentum(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamInput_TranslateActionOrigin(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamInput_TriggerSimpleHapticEvent(void) {}
VD_EXPORT void SteamAPI_ISteamInput_TriggerVibration(void) {}
VD_EXPORT void SteamAPI_ISteamInput_TriggerVibrationExtended(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamInventory_AddPromoItem(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_AddPromoItems(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_CheckResultSteamID(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_ConsumeItem(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_DeserializeResult(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamInventory_DestroyResult(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamInventory_ExchangeItems(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_GenerateItems(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_GetAllItems(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_GetEligiblePromoItemDefinitionIDs(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_GetItemDefinitionIDs(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_GetItemDefinitionProperty(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_GetItemPrice(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_GetItemsByID(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_GetItemsWithPrices(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_GetNumItemsWithPrices(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_GetResultItemProperty(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_GetResultItems(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_GetResultStatus(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_GetResultTimestamp(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_GrantPromoItems(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_InspectItem(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_LoadItemDefinitions(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_RemoveProperty(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_RequestEligiblePromoItemDefinitionsIDs(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_RequestPrices(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamInventory_SendItemDropHeartbeat(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamInventory_SerializeResult(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_SetPropertyBool(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_SetPropertyFloat(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_SetPropertyInt64(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_SetPropertyString(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_StartPurchase(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_StartUpdateProperties(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_SubmitUpdateProperties(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_TradeItems(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_TransferItemQuantity(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamInventory_TriggerItemDrop(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamMatchmakingServers_CancelQuery(void) {}
VD_EXPORT void SteamAPI_ISteamMatchmakingServers_CancelServerQuery(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamMatchmakingServers_GetServerCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmakingServers_GetServerDetails(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmakingServers_IsRefreshing(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmakingServers_PingServer(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmakingServers_PlayerDetails(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamMatchmakingServers_RefreshQuery(void) {}
VD_EXPORT void SteamAPI_ISteamMatchmakingServers_RefreshServer(void) {}
VD_EXPORT void SteamAPI_ISteamMatchmakingServers_ReleaseRequest(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamMatchmakingServers_RequestFavoritesServerList(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmakingServers_RequestFriendsServerList(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmakingServers_RequestHistoryServerList(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmakingServers_RequestInternetServerList(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmakingServers_RequestLANServerList(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmakingServers_RequestSpectatorServerList(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmakingServers_ServerRules(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_AddFavoriteGame(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamMatchmaking_AddRequestLobbyListCompatibleMembersFilter(void) {}
VD_EXPORT void SteamAPI_ISteamMatchmaking_AddRequestLobbyListDistanceFilter(void) {}
VD_EXPORT void SteamAPI_ISteamMatchmaking_AddRequestLobbyListFilterSlotsAvailable(void) {}
VD_EXPORT void SteamAPI_ISteamMatchmaking_AddRequestLobbyListNearValueFilter(void) {}
VD_EXPORT void SteamAPI_ISteamMatchmaking_AddRequestLobbyListNumericalFilter(void) {}
VD_EXPORT void SteamAPI_ISteamMatchmaking_AddRequestLobbyListResultCountFilter(void) {}
VD_EXPORT void SteamAPI_ISteamMatchmaking_AddRequestLobbyListStringFilter(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_CreateLobby(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_DeleteLobbyData(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_GetFavoriteGame(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_GetFavoriteGameCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_GetLobbyByIndex(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_GetLobbyChatEntry(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_GetLobbyData(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_GetLobbyDataByIndex(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_GetLobbyDataCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_GetLobbyGameServer(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_GetLobbyMemberByIndex(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_GetLobbyMemberData(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_GetLobbyMemberLimit(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_GetLobbyOwner(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_GetNumLobbyMembers(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_InviteUserToLobby(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_JoinLobby(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamMatchmaking_LeaveLobby(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_RemoveFavoriteGame(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_RequestLobbyData(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_RequestLobbyList(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_SendLobbyChatMsg(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_SetLinkedLobby(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_SetLobbyData(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamMatchmaking_SetLobbyGameServer(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_SetLobbyJoinable(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamMatchmaking_SetLobbyMemberData(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_SetLobbyMemberLimit(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_SetLobbyOwner(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMatchmaking_SetLobbyType(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_BActivationSuccess(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_BIsCurrentMusicRemote(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_CurrentEntryDidChange(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_CurrentEntryIsAvailable(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_CurrentEntryWillChange(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_DeregisterSteamMusicRemote(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_EnableLooped(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_EnablePlayNext(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_EnablePlayPrevious(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_EnablePlaylists(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_EnableQueue(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_EnableShuffled(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_PlaylistDidChange(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_PlaylistWillChange(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_QueueDidChange(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_QueueWillChange(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_RegisterSteamMusicRemote(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_ResetPlaylistEntries(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_ResetQueueEntries(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_SetCurrentPlaylistEntry(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_SetCurrentQueueEntry(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_SetDisplayName(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_SetPNGIcon_64x64(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_SetPlaylistEntry(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_SetQueueEntry(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_UpdateCurrentEntryCoverArt(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_UpdateCurrentEntryElapsedSeconds(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_UpdateCurrentEntryText(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_UpdateLooped(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_UpdatePlaybackStatus(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_UpdateShuffled(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusicRemote_UpdateVolume(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusic_BIsEnabled(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusic_BIsPlaying(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamMusic_GetPlaybackStatus(void) { return 0; }
VD_EXPORT float SteamAPI_ISteamMusic_GetVolume(void) { return 0.0f; }
VD_EXPORT void SteamAPI_ISteamMusic_Pause(void) {}
VD_EXPORT void SteamAPI_ISteamMusic_Play(void) {}
VD_EXPORT void SteamAPI_ISteamMusic_PlayNext(void) {}
VD_EXPORT void SteamAPI_ISteamMusic_PlayPrevious(void) {}
VD_EXPORT void SteamAPI_ISteamMusic_SetVolume(void) {}
VD_EXPORT void SteamAPI_ISteamNetworkingConnectionSignaling_Release(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingConnectionSignaling_SendSignal(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingMessages_AcceptSessionWithUser(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingMessages_CloseChannelWithUser(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingMessages_CloseSessionWithUser(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingMessages_GetSessionConnectionInfo(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingMessages_ReceiveMessagesOnChannel(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingMessages_SendMessageToUser(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSignalingRecvContext_OnConnectRequest(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamNetworkingSignalingRecvContext_SendRejectionSignal(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_AcceptConnection(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_BeginAsyncRequestFakeIP(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_CloseConnection(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_CloseListenSocket(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_ConfigureConnectionLanes(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_ConnectByIPAddress(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_ConnectP2P(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_ConnectP2PCustomSignaling(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_ConnectToHostedDedicatedServer(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_CreateFakeUDPPort(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_CreateHostedDedicatedServerListenSocket(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_CreateListenSocketIP(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_CreateListenSocketP2P(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_CreateListenSocketP2PFakeIP(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_CreatePollGroup(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_CreateSocketPair(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_DestroyPollGroup(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_FindRelayAuthTicketForServer(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_FlushMessagesOnConnection(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_GetAuthenticationStatus(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_GetCertificateRequest(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_GetConnectionInfo(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_GetConnectionName(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_GetConnectionRealTimeStatus(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_GetConnectionUserData(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_GetDetailedConnectionStatus(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamNetworkingSockets_GetFakeIP(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_GetGameCoordinatorServerLogin(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_GetHostedDedicatedServerAddress(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_GetHostedDedicatedServerPOPID(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_GetHostedDedicatedServerPort(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_GetIdentity(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_GetListenSocketAddress(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_GetRemoteFakeIPForConnection(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_InitAuthentication(void) { return 100; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_ReceiveMessagesOnConnection(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_ReceiveMessagesOnPollGroup(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_ReceivedP2PCustomSignal(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_ReceivedRelayAuthTicket(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamNetworkingSockets_ResetIdentity(void) {}
VD_EXPORT void SteamAPI_ISteamNetworkingSockets_RunCallbacks(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_SendMessageToConnection(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamNetworkingSockets_SendMessages(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_SetCertificate(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamNetworkingSockets_SetConnectionName(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_SetConnectionPollGroup(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingSockets_SetConnectionUserData(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_AllocateMessage(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_CheckPingDataUpToDate(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamNetworkingUtils_ConvertPingLocationToString(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_EstimatePingTimeBetweenTwoLocations(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_EstimatePingTimeFromLocalHost(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_GetConfigValue(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_GetConfigValueInfo(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_GetDirectPingToPOP(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_GetIPv4FakeIPType(void) { return 0; }
VD_EXPORT float SteamAPI_ISteamNetworkingUtils_GetLocalPingLocation(void) { return 0.0f; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_GetLocalTimestamp(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_GetPOPCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_GetPOPList(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_GetPingToDataCenter(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_GetRealIdentityForFakeIP(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_GetRelayNetworkStatus(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamNetworkingUtils_InitRelayNetworkAccess(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_IsFakeIPv4(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_IterateGenericEditableConfigValues(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_ParsePingLocationString(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_SetConfigValue(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamNetworkingUtils_SetDebugOutputFunction(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_SteamNetworkingIPAddr_GetFakeIPType(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_SteamNetworkingIPAddr_ParseString(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamNetworkingUtils_SteamNetworkingIPAddr_ToString(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamNetworkingUtils_SteamNetworkingIdentity_ParseString(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamNetworkingUtils_SteamNetworkingIdentity_ToString(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_AcceptP2PSessionWithUser(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_AllowP2PPacketRelay(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_CloseP2PChannelWithUser(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_CloseP2PSessionWithUser(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_CreateConnectionSocket(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_CreateListenSocket(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_CreateP2PConnectionSocket(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_DestroyListenSocket(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_DestroySocket(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_GetListenSocketInfo(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_GetMaxPacketSize(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_GetP2PSessionState(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_GetSocketConnectionType(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_GetSocketInfo(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_IsDataAvailable(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_IsDataAvailableOnSocket(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_IsP2PPacketAvailable(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_ReadP2PPacket(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_RetrieveData(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_RetrieveDataFromSocket(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_SendDataOnSocket(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamNetworking_SendP2PPacket(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamParentalSettings_BIsAppBlocked(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamParentalSettings_BIsAppInBlockList(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamParentalSettings_BIsFeatureBlocked(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamParentalSettings_BIsFeatureInBlockList(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamParentalSettings_BIsParentalLockEnabled(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamParentalSettings_BIsParentalLockLocked(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamParties_CancelReservation(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamParties_ChangeNumOpenSlots(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamParties_CreateBeacon(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamParties_DestroyBeacon(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamParties_GetAvailableBeaconLocations(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamParties_GetBeaconByIndex(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamParties_GetBeaconDetails(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamParties_GetBeaconLocationData(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamParties_GetNumActiveBeacons(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamParties_GetNumAvailableBeaconLocations(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamParties_JoinParty(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamParties_OnReservationCompleted(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamRemotePlay_BGetSessionClientResolution(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemotePlay_BSendRemotePlayTogetherInvite(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemotePlay_GetSessionClientFormFactor(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemotePlay_GetSessionClientName(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemotePlay_GetSessionCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemotePlay_GetSessionID(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemotePlay_GetSessionSteamID(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_BeginFileWriteBatch(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_CommitPublishedFileUpdate(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_CreatePublishedFileUpdateRequest(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_DeletePublishedFile(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_EndFileWriteBatch(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_EnumeratePublishedFilesByUserAction(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_EnumeratePublishedWorkshopFiles(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_EnumerateUserPublishedFiles(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_EnumerateUserSharedWorkshopFiles(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_EnumerateUserSubscribedFiles(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_FileDelete(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_FileExists(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_FileForget(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_FilePersisted(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_FileRead(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_FileReadAsync(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_FileReadAsyncComplete(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_FileShare(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_FileWrite(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_FileWriteAsync(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_FileWriteStreamCancel(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_FileWriteStreamClose(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_FileWriteStreamOpen(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_FileWriteStreamWriteChunk(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_GetCachedUGCCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_GetCachedUGCHandle(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_GetFileCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_GetFileNameAndSize(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_GetFileSize(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_GetFileTimestamp(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_GetLocalFileChange(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_GetLocalFileChangeCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_GetPublishedFileDetails(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_GetPublishedItemVoteDetails(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_GetQuota(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_GetSyncPlatforms(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_GetUGCDetails(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_GetUGCDownloadProgress(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_GetUserPublishedItemVoteDetails(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_IsCloudEnabledForAccount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_IsCloudEnabledForApp(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_PublishVideo(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_PublishWorkshopFile(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamRemoteStorage_SetCloudEnabledForApp(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_SetSyncPlatforms(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_SetUserPublishedFileAction(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_SubscribePublishedFile(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_UGCDownload(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_UGCDownloadToLocation(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_UGCRead(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_UnsubscribePublishedFile(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_UpdatePublishedFileDescription(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_UpdatePublishedFileFile(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_UpdatePublishedFilePreviewFile(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_UpdatePublishedFileSetChangeDescription(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_UpdatePublishedFileTags(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_UpdatePublishedFileTitle(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_UpdatePublishedFileVisibility(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamRemoteStorage_UpdateUserPublishedItemVote(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamScreenshots_AddScreenshotToLibrary(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamScreenshots_AddVRScreenshotToLibrary(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamScreenshots_HookScreenshots(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamScreenshots_IsScreenshotsHooked(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamScreenshots_SetLocation(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamScreenshots_TagPublishedFile(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamScreenshots_TagUser(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamScreenshots_TriggerScreenshot(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamScreenshots_WriteScreenshot(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_AddAppDependency(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_AddContentDescriptor(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_AddDependency(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_AddExcludedTag(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_AddItemKeyValueTag(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_AddItemPreviewFile(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_AddItemPreviewVideo(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_AddItemToFavorites(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_AddRequiredKeyValueTag(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_AddRequiredTag(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_AddRequiredTagGroup(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_BInitWorkshopForGameServer(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_CreateItem(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_CreateQueryAllUGCRequestCursor(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_CreateQueryAllUGCRequestPage(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_CreateQueryUGCDetailsRequest(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_CreateQueryUserUGCRequest(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_DeleteItem(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_DownloadItem(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetAppDependencies(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetItemDownloadInfo(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetItemInstallInfo(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetItemState(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetItemUpdateProgress(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetNumSubscribedItems(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetQueryFirstUGCKeyValueTag(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetQueryUGCAdditionalPreview(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetQueryUGCChildren(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetQueryUGCContentDescriptors(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetQueryUGCKeyValueTag(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetQueryUGCMetadata(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetQueryUGCNumAdditionalPreviews(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetQueryUGCNumKeyValueTags(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetQueryUGCNumTags(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetQueryUGCPreviewURL(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetQueryUGCResult(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetQueryUGCStatistic(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetQueryUGCTag(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetQueryUGCTagDisplayName(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetSubscribedItems(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetUserItemVote(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_GetWorkshopEULAStatus(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_ReleaseQueryUGCRequest(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_RemoveAllItemKeyValueTags(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_RemoveAppDependency(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_RemoveContentDescriptor(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_RemoveDependency(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_RemoveItemFromFavorites(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_RemoveItemKeyValueTags(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_RemoveItemPreview(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_RequestUGCDetails(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SendQueryUGCRequest(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetAllowCachedResponse(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetAllowLegacyUpload(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetCloudFileNameFilter(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetItemContent(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetItemDescription(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetItemMetadata(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetItemPreview(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetItemTags(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetItemTitle(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetItemUpdateLanguage(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetItemVisibility(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetLanguage(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetMatchAnyTag(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetRankedByTrendDays(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetReturnAdditionalPreviews(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetReturnChildren(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetReturnKeyValueTags(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetReturnLongDescription(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetReturnMetadata(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetReturnOnlyIDs(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetReturnPlaytimeStats(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetReturnTotalOnly(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetSearchText(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetTimeCreatedDateRange(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetTimeUpdatedDateRange(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SetUserItemVote(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_ShowWorkshopEULA(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_StartItemUpdate(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_StartPlaytimeTracking(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_StopPlaytimeTracking(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_StopPlaytimeTrackingForAllItems(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SubmitItemUpdate(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_SubscribeItem(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamUGC_SuspendDownloads(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamUGC_UnsubscribeItem(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_UpdateItemPreviewFile(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUGC_UpdateItemPreviewVideo(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_AttachLeaderboardUGC(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_ClearAchievement(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_DownloadLeaderboardEntries(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_DownloadLeaderboardEntriesForUsers(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_FindLeaderboard(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_FindOrCreateLeaderboard(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetAchievement(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetAchievementAchievedPercent(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetAchievementAndUnlockTime(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetAchievementDisplayAttribute(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetAchievementIcon(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetAchievementName(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetAchievementProgressLimitsFloat(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetAchievementProgressLimitsInt32(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetDownloadedLeaderboardEntry(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetGlobalStatDouble(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetGlobalStatHistoryDouble(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetGlobalStatHistoryInt64(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetGlobalStatInt64(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetLeaderboardDisplayType(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetLeaderboardEntryCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetLeaderboardName(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetLeaderboardSortMethod(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetMostAchievedAchievementInfo(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetNextMostAchievedAchievementInfo(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetNumAchievements(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetNumberOfCurrentPlayers(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetStatFloat(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetStatInt32(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetUserAchievement(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetUserAchievementAndUnlockTime(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetUserStatFloat(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_GetUserStatInt32(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_IndicateAchievementProgress(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_RequestCurrentStats(void) { return 1; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_RequestGlobalAchievementPercentages(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_RequestGlobalStats(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_RequestUserStats(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_ResetAllStats(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_SetAchievement(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_SetStatFloat(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_SetStatInt32(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_StoreStats(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_UpdateAvgRateStat(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUserStats_UploadLeaderboardScore(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamUser_AdvertiseGame(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamUser_BIsBehindNAT(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_BIsPhoneIdentifying(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_BIsPhoneRequiringVerification(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_BIsPhoneVerified(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_BIsTwoFactorEnabled(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_BLoggedOn(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_BSetDurationControlOnlineState(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_BeginAuthSession(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamUser_CancelAuthTicket(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamUser_DecompressVoice(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamUser_EndAuthSession(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamUser_GetAuthSessionTicket(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_GetAuthTicketForWebApi(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_GetAvailableVoice(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_GetDurationControl(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_GetEncryptedAppTicket(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_GetGameBadgeLevel(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_GetHSteamUser(void) { return 1; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_GetMarketEligibility(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_GetPlayerSteamLevel(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_GetSteamID(void) { return 76561197960287930ULL; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_GetUserDataFolder(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_GetVoice(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_GetVoiceOptimalSampleRate(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_InitiateGameConnection_DEPRECATED(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_RequestEncryptedAppTicket(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUser_RequestStoreAuthURL(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamUser_StartVoiceRecording(void) {}
VD_EXPORT void SteamAPI_ISteamUser_StopVoiceRecording(void) {}
VD_EXPORT void SteamAPI_ISteamUser_TerminateGameConnection_DEPRECATED(void) {}
VD_EXPORT void SteamAPI_ISteamUser_TrackAppUsageEvent(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamUser_UserHasLicenseForApp(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_BOverlayNeedsPresent(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_CheckFileSignature(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_DismissFloatingGamepadTextInput(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_FilterText(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_GetAPICallFailureReason(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_GetAPICallResult(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_GetAppID(void) { return 892970U; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_GetConnectedUniverse(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_GetCurrentBatteryPower(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_GetEnteredGamepadTextInput(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_GetEnteredGamepadTextLength(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_GetIPCCallCount(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_GetIPCountry(void) { return (uint64_t)(uintptr_t)vd_country; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_GetIPv6ConnectivityState(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_GetImageRGBA(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_GetImageSize(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_GetSecondsSinceAppActive(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_GetSecondsSinceComputerActive(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_GetServerRealTime(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_GetSteamUILanguage(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_InitFilterText(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_IsAPICallCompleted(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_IsOverlayEnabled(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_IsSteamChinaLauncher(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_IsSteamInBigPictureMode(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_IsSteamRunningInVR(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_IsSteamRunningOnSteamDeck(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_IsVRHeadsetStreamingEnabled(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamUtils_SetGameLauncherMode(void) {}
VD_EXPORT void SteamAPI_ISteamUtils_SetOverlayNotificationInset(void) {}
VD_EXPORT void SteamAPI_ISteamUtils_SetOverlayNotificationPosition(void) {}
VD_EXPORT void SteamAPI_ISteamUtils_SetVRHeadsetStreamingEnabled(void) {}
VD_EXPORT void SteamAPI_ISteamUtils_SetWarningMessageHook(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamUtils_ShowFloatingGamepadTextInput(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ISteamUtils_ShowGamepadTextInput(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamUtils_StartVRDashboard(void) {}
VD_EXPORT void SteamAPI_ISteamVideo_GetOPFSettings(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamVideo_GetOPFStringForApp(void) { return 0; }
VD_EXPORT void SteamAPI_ISteamVideo_GetVideoURL(void) {}
VD_EXPORT uint64_t SteamAPI_ISteamVideo_IsBroadcasting(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_Init(void) { return 1; }
VD_EXPORT uint64_t SteamAPI_IsSteamRunning(void) { return 1; }
VD_EXPORT void SteamAPI_ManualDispatch_FreeLastCallback(void) {}
VD_EXPORT uint64_t SteamAPI_ManualDispatch_GetAPICallResult(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_ManualDispatch_GetNextCallback(void) { return 0; }
VD_EXPORT void SteamAPI_ManualDispatch_Init(void) {}
VD_EXPORT void SteamAPI_ManualDispatch_RunFrame(void) {}
VD_EXPORT void SteamAPI_RegisterCallResult(void) {}
VD_EXPORT void SteamAPI_RegisterCallback(void) {}
VD_EXPORT void SteamAPI_ReleaseCurrentThreadMemory(void) {}
VD_EXPORT uint64_t SteamAPI_RestartAppIfNecessary(void) { return 0; }
VD_EXPORT void SteamAPI_RunCallbacks(void) {}
VD_EXPORT void SteamAPI_SetBreakpadAppID(void) {}
VD_EXPORT void SteamAPI_SetMiniDumpComment(void) {}
VD_EXPORT void SteamAPI_SetTryCatchCallbacks(void) {}
VD_EXPORT void SteamAPI_Shutdown(void) {}
VD_EXPORT void SteamAPI_SteamNetworkingIPAddr_Clear(void) {}
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIPAddr_GetFakeIPType(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIPAddr_GetIPv4(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIPAddr_IsEqualTo(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIPAddr_IsFakeIP(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIPAddr_IsIPv4(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIPAddr_IsIPv6AllZeros(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIPAddr_IsLocalHost(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIPAddr_ParseString(void) { return 0; }
VD_EXPORT void SteamAPI_SteamNetworkingIPAddr_SetIPv4(void) {}
VD_EXPORT void SteamAPI_SteamNetworkingIPAddr_SetIPv6(void) {}
VD_EXPORT void SteamAPI_SteamNetworkingIPAddr_SetIPv6LocalHost(void) {}
VD_EXPORT void SteamAPI_SteamNetworkingIPAddr_ToString(void) {}
VD_EXPORT void SteamAPI_SteamNetworkingIdentity_Clear(void) {}
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_GetFakeIPType(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_GetGenericBytes(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_GetGenericString(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_GetIPAddr(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_GetIPv4(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_GetPSNID(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_GetStadiaID(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_GetSteamID(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_GetSteamID64(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_GetXboxPairwiseID(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_IsEqualTo(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_IsFakeIP(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_IsInvalid(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_IsLocalHost(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_ParseString(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_SetGenericBytes(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_SetGenericString(void) { return 0; }
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_SetIPAddr(void) { return 0; }
VD_EXPORT void SteamAPI_SteamNetworkingIdentity_SetIPv4Addr(void) {}
VD_EXPORT void SteamAPI_SteamNetworkingIdentity_SetLocalHost(void) {}
VD_EXPORT void SteamAPI_SteamNetworkingIdentity_SetPSNID(void) {}
VD_EXPORT void SteamAPI_SteamNetworkingIdentity_SetStadiaID(void) {}
VD_EXPORT void SteamAPI_SteamNetworkingIdentity_SetSteamID(void) {}
VD_EXPORT void SteamAPI_SteamNetworkingIdentity_SetSteamID64(void) {}
VD_EXPORT uint64_t SteamAPI_SteamNetworkingIdentity_SetXboxPairwiseID(void) { return 0; }
VD_EXPORT void SteamAPI_SteamNetworkingIdentity_ToString(void) {}
VD_EXPORT void SteamAPI_SteamNetworkingMessage_t_Release(void) {}
VD_EXPORT void SteamAPI_UnregisterCallResult(void) {}
VD_EXPORT void SteamAPI_UnregisterCallback(void) {}
VD_EXPORT void SteamAPI_UseBreakpadCrashHandler(void) {}
VD_EXPORT void SteamAPI_WriteMiniDump(void) {}
VD_EXPORT uint64_t SteamClient(void) { return 0; }
VD_EXPORT uint64_t SteamGameServerClient(void) { return 0; }
VD_EXPORT uint64_t SteamGameServer_BSecure(void) { return 0; }
VD_EXPORT uint64_t SteamGameServer_GetHSteamPipe(void) { return 0; }
VD_EXPORT uint64_t SteamGameServer_GetHSteamUser(void) { return 0; }
VD_EXPORT uint64_t SteamGameServer_GetSteamID(void) { return 0; }
VD_EXPORT void SteamGameServer_ReleaseCurrentThreadMemory(void) {}
VD_EXPORT void SteamGameServer_RunCallbacks(void) {}
VD_EXPORT void SteamGameServer_Shutdown(void) {}
VD_EXPORT uint64_t SteamInternal_ContextInit(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamInternal_CreateInterface(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamInternal_FindOrCreateGameServerInterface(void) { return 0; }
VD_EXPORT uint64_t SteamInternal_FindOrCreateUserInterface(void) { return (uint64_t)(uintptr_t)vd_interface; }
VD_EXPORT uint64_t SteamInternal_GameServer_Init(void) { return 0; }
